keys:
  - &dev age1w30vy5gwwxzqf98zmj2e2s54e9zua6r279xtcxrdr3jq25e0tczq47dl5l
  - &linode age1er0m2t7s47twdd085rjfhpymjca4m3vcrcrm2k6j766p7q5fau0q7dycdm
  - &mac age1zfg2l635tj8zsc5nc7hfpa2h4adxu978rymmn6nqjk8dzvwle92qs9ggae
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
        - *dev
        - *linode
        - *mac
