theme = "slick"
icons = "awesome"

[[block]]
block = "custom"
command = "echo NixOS: $(nixos-version)/$(uname -r)"
interval = 100

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "net"
device = "wlp3s0"
interval = 5

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used}/{mem_total}({mem_used_percents})"
format_swap = "{swap_used}/{swap_total}({swap_used_percents})"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "time"
interval = 60
format = "(US) %a %m/%d %R"

[[block]]
block = "time"
interval = 60
format = "(TN) %R"
timezone = "Africa/Tunis"

